language: node_js
node_js:
  - 6
services:
  - docker

jobs:
  include:
  - stage: build and test
    script:
    - npm test
  - if: (NOT type IN (pull_request)) AND (branch = master)
    script:
    - npm run-script docker-build
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - npm run-script docker-push